var arrayVerb = [];

function loadVerb(){ 
    arrayVerb.push([ "ser/estar", "be", "was/were", "been"]);
    arrayVerb.push([ "ganarle", "beat", "beat", "beaten" ]);
    arrayVerb.push([ "empezar", "begin", "began", "begun" ]);
    arrayVerb.push([ "doblar", "bend", "bent", "bent" ]);
    arrayVerb.push([ "morder", "bite", "bit", "bitten" ]);
    arrayVerb.push([ "soplar", "blow", "blew", "blown" ]);
    arrayVerb.push([ "romper", "break", "broke", "broken" ]);
    arrayVerb.push([ "traer", "bring", "brought", "brought" ]);
    arrayVerb.push([ "construir", "build", "built", "built" ]);
    arrayVerb.push([ "comprar", "buy", "bought", "bought" ]);
    arrayVerb.push([ "coger", "catch", "caught", "caught" ]);
    arrayVerb.push([ "elegir", "choose", "chose", "chosen" ]);
    arrayVerb.push([ "venir", "come", "came", "come" ]);
    arrayVerb.push([ "costar", "cost", "cost", "cost" ]);
    arrayVerb.push([ "hacer", "do", "did", "done" ]);
    arrayVerb.push([ "dibujar", "draw", "drew", "drawn" ]);
    arrayVerb.push([ "soñar", "dream", "dreamed,dreamt", "dreamed,dreamt" ]);
    arrayVerb.push([ "conducir", "drive", "drove", "driven" ]);
    arrayVerb.push([ "beber", "drink", "drank", "drunk" ]);
    arrayVerb.push([ "comer", "eat", "ate", "eaten" ]);
    arrayVerb.push([ "caer", "fall", "fell", "fallen" ]);
    arrayVerb.push([ "sentir", "feel", "felt", "felt" ]);
    arrayVerb.push([ "luchar", "fight", "fought", "fought" ]);
    arrayVerb.push([ "encontrar", "find", "found", "found" ]);
    arrayVerb.push([ "volar", "fly", "flew", "flown" ]);
    arrayVerb.push([ "olvidar", "forget", "forgot", "forgotten" ]);
    arrayVerb.push([ "perdonar", "forgive", "forgave", "forgiven" ]);
    arrayVerb.push([ "conseguir", "get", "got", "gotten" ]);
    arrayVerb.push([ "dar", "give", "gave", "given" ]);
    arrayVerb.push([ "ir", "go", "went", "gone" ]);
    arrayVerb.push([ "crecer", "grow", "grew", "grown" ]);
    arrayVerb.push([ "tener", "have", "had", "had" ]);
    arrayVerb.push([ "oír", "hear", "heard", "heard" ]);
    arrayVerb.push([ "esconder", "hide", "hid", "hidden" ]);
    arrayVerb.push([ "golpear", "hit", "hit", "hit" ]);
    arrayVerb.push([ "sujetar", "hold", "held", "held" ]);
    arrayVerb.push([ "doler, hacer daño", "hurt", "hurt", "hurt" ]);
    arrayVerb.push([ "guardar", "keep", "kept", "kept" ]);
    arrayVerb.push([ "saber", "know", "knew", "known" ]);
    arrayVerb.push([ "aprender", "learn", "learned,learnt", "learned,learnt" ]);
    arrayVerb.push([ "marcharse", "leave", "left", "left" ]);
    arrayVerb.push([ "prestar", "lend", "lent", "lent" ]);
    arrayVerb.push([ "permitir", "let", "let", "let" ]);
    arrayVerb.push([ "perder", "lose", "lost", "lost" ]);
    arrayVerb.push([ "hacer", "make", "made", "made" ]);
    arrayVerb.push([ "querer decir", "mean", "meant", "meant" ]);
    arrayVerb.push([ "quedar", "meet", "met", "met" ]);
    arrayVerb.push([ "pagar", "pay", "paid", "paid" ]);
    arrayVerb.push([ "poner", "put", "put", "put" ]);
    arrayVerb.push([ "leer", "read", "read", "read" ]);
    arrayVerb.push([ "sonar", "ring", "rang", "rung" ]);
    arrayVerb.push([ "levantar", "rise", "rose", "risen" ]);
    arrayVerb.push([ "correr", "run", "ran", "run" ]);
    arrayVerb.push([ "decir", "say", "said", "said" ]);
    arrayVerb.push([ "ver", "see", "saw", "seen" ]);
    arrayVerb.push([ "vender", "sell", "sold", "sold" ]);
    arrayVerb.push([ "enviar", "send", "sent", "sent" ]);
    arrayVerb.push([ "mostrar", "show", "showed", "showed, shown" ]);
    arrayVerb.push([ "cerrar", "shut", "shut", "shut" ]);
    arrayVerb.push([ "cantar", "sing", "sang", "sung" ]);
    arrayVerb.push([ "sentarse", "sit", "sat", "sat" ]);
    arrayVerb.push([ "dormir", "sleep", "slept", "slept" ]);
    arrayVerb.push([ "hablar", "speak", "spoke", "spoken" ]);
    arrayVerb.push([ "gastar", "spend", "spent", "spent" ]);
    arrayVerb.push([ "estar de pie", "stand", "stood", "stood" ]);
    arrayVerb.push([ "nadar", "swim", "swam", "swum" ]);
    arrayVerb.push([ "tomar", "take", "took", "taken" ]);
    arrayVerb.push([ "enseñar", "teach", "taught", "taught" ]);
    arrayVerb.push([ "contar, decirle a alguien", "tell", "told", "told" ]);
    arrayVerb.push([ "pensar", "think", "thought", "thought" ]);
    arrayVerb.push([ "lanzar, arrojar", "throw", "threw", "thrown" ]);
    arrayVerb.push([ "entender", "understand", "understood", "understood" ]);
    arrayVerb.push([ "despertar", "wake", "woke", "woken" ]);
    arrayVerb.push([ "ponerse", "wear", "wore", "worn" ]);
    arrayVerb.push([ "ganar", "win", "won", "won" ]);
    arrayVerb.push([ "escribir", "write", "wrote", "written"] );
}