function loadVerb(arrayVerb){ 
	arrayVerb.push(["ser,estar", "be", "was,were", "been"]);
	arrayVerb.push(["derrotar,vencer", "beat", "beat", "beaten"]);
	arrayVerb.push(["convertirse en, hacerse", "become", "became", "become"]);
	arrayVerb.push(["empezar", "begin", "began", "begun"]);
	arrayVerb.push(["doblar, torcer", "bend", "bent", "bent"]);
	arrayVerb.push(["morder, picar", "bite", "bite", "bitten"]);
	arrayVerb.push(["soplar", "blow", "blew", "blown"]);
	arrayVerb.push(["romper", "break", "broke", "broken"]);
	arrayVerb.push(["traer", "bring", "brought", "brought"]);
	arrayVerb.push(["construir", "build", "built", "built"]);
	arrayVerb.push(["quemar, arder", "burn", "burnt/burned", "burnt/burned"]);
	arrayVerb.push(["comprar", "buy", "bought", "bought"]);
	arrayVerb.push(["coger", "catch", "caught", "caught"]);
	arrayVerb.push(["escoger, elegir", "choose", "chose", "chosen"]);
	arrayVerb.push(["venir", "come", "came", "come"]);
	arrayVerb.push(["valer", "cost", "cost", "cost"]);
	arrayVerb.push(["cortar", "cut", "cut", "cut"]);
	arrayVerb.push(["cavar", "dig", "dug", "dug"]);
	arrayVerb.push(["hacer", "do", "did", "done"]);
	arrayVerb.push(["dibujar", "draw", "drew", "drawn"]);
	arrayVerb.push(["soñar", "dream", "dreamt/dreamed", "deamt/dreamed"]);
	arrayVerb.push(["beber", "drink", "drank", "drunk"]);
	arrayVerb.push(["conducir", "drive", "drove", "droven"]);
	arrayVerb.push(["comer", "eat", "ate", "eaten"]);
	arrayVerb.push(["caer", "fall", "fell", "fallen"]);
	arrayVerb.push(["alimentar", "feed", "fed", "fed"]);
	arrayVerb.push(["sentir", "feel", "felt", "felt"]);
	arrayVerb.push(["luchar", "fight", "fought", "fought"]);
	arrayVerb.push(["encontrar", "find", "found", "found"]);
	arrayVerb.push(["volar", "fly", "flew", "flown"]);
	arrayVerb.push(["olvidar", "forget", "forgot", "forgotten"]);
	arrayVerb.push(["perdonar", "forgive", "forgave", "forgiven"]);
	arrayVerb.push(["congelar", "freeze", "froze", "frozen"]);
	arrayVerb.push(["conseguir,obtener", "get", "got", "got"]);
	arrayVerb.push(["dar", "give", "gave", "given"]);
	arrayVerb.push(["ir", "got", "went", "gone"]);
	arrayVerb.push(["crecer, cultivar", "grow", "grew", "grown"]);
	arrayVerb.push(["colgar", "hang", "hung", "hung"]);
	arrayVerb.push(["tener", "have", "had", "had"]);
	arrayVerb.push(["oír", "hear", "heard", "heard"]);
	arrayVerb.push(["esconder", "hide", "hid", "hidden"]);
	arrayVerb.push(["golpear,pegar", "hit", "hit", "hit"]);
	arrayVerb.push(["sujetar", "hold", "held", "held"]);
	arrayVerb.push(["hacer daño, doler", "hurt", "hurt", "hurt"]);
	arrayVerb.push(["continuar, mantener", "keep", "kept", "kept"]);
	arrayVerb.push(["saber,conocer", "know", "knew", "known"]);
	arrayVerb.push(["extender, poner", "lay", "laid", "laid"]);
	arrayVerb.push(["guiar", "lead", "led", "led"]);
	arrayVerb.push(["aprender", "learn", "learnt/learned", "learnt/learned"]);
	arrayVerb.push(["irse,dejar", "leave", "left", "left"]);
	arrayVerb.push(["prestar", "lend", "lent", "lent"]);
	arrayVerb.push(["permitir, dejar", "let", "let", "let"]);
	arrayVerb.push(["encender", "light", "lit", "lit"]);
	arrayVerb.push(["perder", "lose", "lost", "lost"]);
	arrayVerb.push(["hacer, fabricar", "make", "made", "made"]);
	arrayVerb.push(["significar, querer decir", "mean", "meant", "meant"]);
	arrayVerb.push(["conocer, quedar con", "meet", "met", "met"]);
	arrayVerb.push(["pagar", "pay", "paid", "paid"]);
	arrayVerb.push(["poner", "put", "put", "put"]);
	arrayVerb.push(["leer", "read", "read", "read"]);
	arrayVerb.push(["montar", "ride", "rode", "ridden"]);
	arrayVerb.push(["llamar por teléfono", "ring", "rang", "rung"]);
	arrayVerb.push(["subir,elevarse", "rise", "rose", "risen"]);
	arrayVerb.push(["correr", "run", "ran", "run"]);
	arrayVerb.push(["decir", "say", "said", "said"]);
	arrayVerb.push(["ver", "see", "saw", "seen"]);
	arrayVerb.push(["vender", "sell", "sold", "sold"]);
	arrayVerb.push(["enviar", "send", "sent", "sent"]);
	arrayVerb.push(["establecer", "set", "set", "set"]);
	arrayVerb.push(["agitar", "shake", "shook", "shaken"]);
	arrayVerb.push(["brillar, relucir", "shine", "shone", "shone"]);
	arrayVerb.push(["cerrar", "shut", "shut", "shut"]);
	arrayVerb.push(["disparar", "shoot", "shot", "shot"]);
	arrayVerb.push(["mostrar", "show", "showed", "shown"]);
	arrayVerb.push(["cantar", "sing", "sang", "sung"]);
	arrayVerb.push(["sentarse", "sit", "sat", "sat"]);
	arrayVerb.push(["dormir", "sleep", "slept", "slept"]);
	arrayVerb.push(["oler", "smell", "smelt/smelled", "smelt/smelled"]);
	arrayVerb.push(["hablar", "speak", "spoke", "spoken"]);
	arrayVerb.push(["deletrear", "spell", "spelt", "spelt"]);
	arrayVerb.push(["gastar,pasar tiempo", "spend", "spent", "spent"]);
	arrayVerb.push(["estar de pie", "stand", "stood", "stood"]);
	arrayVerb.push(["robar", "steal", "stole", "stolen"]);
	arrayVerb.push(["pegar con pegamento", "stick", "stuck", "stuck"]);
	arrayVerb.push(["nadar", "swim", "swam", "swum"]);
	arrayVerb.push(["coger, llevarse", "take", "took", "taken"]);
	arrayVerb.push(["enseñar, dar clase", "teach", "taught", "taught"]);
	arrayVerb.push(["decir, contar", "tell", "told", "told"]);
	arrayVerb.push(["pensar,creer, opinar", "think", "thought", "thought"]);
	arrayVerb.push(["lanzar,tirar", "throw", "threw", "thrown"]);
	arrayVerb.push(["comprender,entender", "understand", "understood", "understood"]);
	arrayVerb.push(["despertar", "wake", "woke", "woken"]);
	arrayVerb.push(["llevar puesto, ponerse", "wear", "wore", "worn"]);
	arrayVerb.push(["ganar", "win", "won", "won"]);
	arrayVerb.push(["escribir", "write", "wrote", "written"]);
    
}